### ISSUE TITLE
Check out header at netlifycms.org, it looks broken

### ISSUE THREAD

**Issue by toiletpatrol** [netlify/netlify-cms-www#18]
I think there is something wrong with your site's header.

**Comment by eliwilliamson** [comment]
@toiletpatrol this looks like it occurred when @bdougie added search to the docs. Fixing now - thank you for letting us know!

**Comment by bdougie** [comment]
Do you mind adding a screenshot of elaborating what is/was broken?

**Comment by toiletpatrol** [comment]
![screenshot 2017-03-27 17 05 54](https://cloud.githubusercontent.com/assets/1193384/24363156/a020defc-1317-11e7-8a26-01f833a7b40b.png)

**Comment by toiletpatrol** [comment]
![screenshot 2017-03-27 18 04 09](https://cloud.githubusercontent.com/assets/1193384/24363214/da9741de-1317-11e7-8855-d7122d374010.png)

**Comment by bdougie** [comment]
Which browser is this? Is this chrome canary?

**Comment by toiletpatrol** [comment]
Google Chrome for Mac 
Version 56.0.2924.87 (64-bit)

**Comment by verythorough** [comment]
Closing as fixed.
