### ISSUE TITLE
Update the GIF/video on homepage

### ISSUE THREAD

**Issue by rafaelconde** [netlify/netlify-cms-www#26]
With the 0.4.0 release, the CMS's UI changed a bit — we should update the video on the homepage to reflect that.

I can take care of this, but just wanted to create the issue for future reference. 👍

**Comment by biilmann** [comment]
Yeps! We better show off the improvements :)

**Comment by erquhart** [comment]
I was thinking this too @rafaelconde, looking forward to it.

**Comment by rafaelconde** [comment]
@erquhart just wondering, do you know of a good demo env to show off?

**Comment by erquhart** [comment]
https://cms-demo.netlify.com

**Comment by rafaelconde** [comment]
@erquhart actually, I don't think that is a good example to show off the CMS, it doesn't have the Editorial Workflow, the preview looks so raw, etc…

**Comment by verythorough** [comment]
Closed by #29
